### ISSUE TITLE
加载插件Wallbreaker总是报错

### ISSUE THREAD

**Issue by yxbbing123** [hluwa/Wallbreaker#17]
objection -g com.adidas.app explore -P objection\plugins\Wallbreaker       加载插件Wallbreaker总是报错，加载别外一个插件dexdump是正常的。
![Uploading 微信图片_20210909095414.png…]()

**Comment by yxbbing123** [comment]
> objection -g com.adidas.app explore -P objection\plugins\Wallbreaker 加载插件Wallbreaker总是报错，加载别外一个插件dexdump是正常的。

![Uploading 20210909095414.png…]()

**Comment by yxbbing123** [comment]
> objection -g com.adidas.app explore -P objection\plugins\Wallbreaker 加载插件Wallbreaker总是报错，加载别外一个插件dexdump是正常的。

Agent injected and responds ok!
[plugin] G:\apkdec\frida\objection\plugins\Wallbreaker\agent does not appear to be a valid plugin. Missing __init__.py

**Comment by jacky1234** [comment]
I met the same issue!

**Comment by hluwa** [comment]
Please `objection -g com.adidas.app explore -P objection\plugins`, sir.
