### ISSUE TITLE
打印参数有误

### ISSUE THREAD

**Issue by fightingman1** [hluwa/Wallbreaker#5]
葫芦娃大佬，我尝试使用WallBreaker对某个方法的参数进行打印。如果只用objection打印的结果是这样的
![image](https://user-images.githubusercontent.com/44536773/92550006-2dbea200-f28d-11ea-9a15-047f3b2351bf.png)
而函数的原型是这样的
![image](https://user-images.githubusercontent.com/44536773/92550051-4333cc00-f28d-11ea-8f4a-356f1e4950ff.png)
也就是说除了第二个参数外，其他两个参数并没有显示其具体的值，二是把他的类显示出来了。在肉丝大佬的推荐下，叫我使用wallbreaker，但是我用wallbreaker dump的结果是这样的
![image](https://user-images.githubusercontent.com/44536773/92550161-7fffc300-f28d-11ea-94a9-2d9ffc0eaea8.png)
问题是我命令用错了，还是环境有问题?

**Comment by hluwa** [comment]
classdump <classname>
