### ISSUE TITLE
一人血书建议下版本优化增加反射深度

### ISSUE THREAD

**Issue by lr-zhao** [hluwa/Wallbreaker#6]
只是个小小建议，可以写个加个递归函数判断类的Filed是否为基础的类型，是的直接输出，否的继续递归获取Filed 的Filed 继续打印。或者像gson的打印object。

**Comment by hluwa** [comment]
那样输出不太好看， field 输出的 handle 就是为了可以让你们手动进行这个操作。

深度分析的功能有在考虑， 但最近没什么时间写代码。

**Comment by 13129761422** [comment]
好看不是次要的么，这工具不是为了懒而写的么

**Comment by hluwa** [comment]
简洁明了好看直观当然是首要的
