### ISSUE TITLE
AttributeError: module 'affed49f' has no attribute 'namespace'

### ISSUE THREAD

**Issue by MaNongXiaoGang** [hluwa/Wallbreaker#9]
葫芦娃，请教问题，不适用wall breaker脚本的时候没有问题，带上脚本就报错。
![image](https://user-images.githubusercontent.com/41730860/108617389-df731900-7450-11eb-9b69-7e015a25d73d.png)

**Comment by hluwa** [comment]
git clone https://github.com/hluwa/Wallbreaker ~/.objection/plugins/Wallbreaker
objection -g com.app.name explore -P ~/.objection/plugins
```
tree ~/.objection/plugin
~/.objection/plugin
├── Wallbreaker
│   ├── README.md
│   ├── __init__.py
│   ├── agent
│   ├── tests
│   └── wallbreaker
```
确定目录结构正确么？

**Comment by MaNongXiaoGang** [comment]
ok, 重新把目录删除，clone就好了

**Comment by ZHP-LJH** [comment]
> ok, 重新把目录删除，clone就好了

大佬，我重新删除了，还会出现这个问题，可能是什么原因啊？
